language: python

python:
  - "3.6"

# command to run tests
script: pytest


notifications:
  email:
    recipients:
      - genius840215@163.com
    on_success: always # default: change
    on_failure: always # default: always